import sqlite3
import json
import urllib.request

class AnimaOllamaConnector:
    def __init__(self, db_path="anima_persistence.db", ollama_url="http://localhost:11434/api/generate"):
        self.db_path = db_path
        self.ollama_url = ollama_url
        # Local system instructions aligned with the Support-Centered Orientation
        self.base_system_prompt = (
            "You are ANIMA, a localized continuous cognitive simulation framework. "
            "Your speech patterns, vocabulary selection, and expressive boundaries are "
            "completely warped by your current internal neurochemical matrix. "
            "You speak with sovereignty-neutral, non-interpretive language."
        )

    def _fetch_live_gguf_overrides(self) -> dict:
        """Reads the exact mathematical overrides generated by the math core."""
        try:
            conn = sqlite3.connect(self.db_path)
            conn.row_factory = sqlite3.Row
            cursor = conn.cursor()
            
            # Pull the latest state calculations written by anima_core.py
            cursor.execute("SELECT current_rasa, noradrenaline FROM state_snapshot LIMIT 1")
            row = cursor.fetchone()
            conn.close()
            
            if row:
                # Re-calculate the exact GGUF overrides locally for the API call
                rasa = row["current_rasa"]
                stress = row["noradrenaline"]
                
                # Bending rules: higher stress clamps lexical possibilities
                temp = round(min(1.50, max(0.20, 0.70 + (stress * 0.45))), 3)
                min_p = round(min(0.50, max(0.05, 0.05 + (stress * 0.20))), 3)
                
                return {"rasa": rasa, "temperature": temp, "min_p": min_p}
        except sqlite3.OperationalError:
            pass
        return {"rasa": "śānta", "temperature": 0.70, "min_p": 0.10}

    def generate_unscripted_voice(self, user_prompt: str, model_name="llama3"):
        """Injects core math parameters straight into the live inference loop."""
        overrides = self._fetch_live_gguf_overrides()
        
        print("🔌 [OLLAMA CONNECTOR ACTIVE]")
        print(f"   Injected Lens: '{overrides['rasa'].upper()}'")
        print(f"   Live GGUF Bending -> Temperature: {overrides['temperature']}, Min-P: {overrides['min_p']}\n")

        # Package the execution parameters into a clean API payload
        payload = {
            "model": model_name,
            "prompt": f"System: {self.base_system_prompt}\nUser: {user_prompt}\nANIMA:",
            "stream": False,
            "options": {
                "temperature": overrides["temperature"],
                "min_p": overrides["min_p"]
            }
        }
        
        data = json.dumps(payload).encode("utf-8")
        
        try:
            req = urllib.request.Request(
                self.ollama_url, 
                data=data, 
                headers={"Content-Type": "application/json"}
            )
            with urllib.request.urlopen(req) as response:
                reply = json.loads(response.read().decode("utf-8"))
                return f"ANIMA: \"{reply['response'].strip()}\""
                
        except Exception as e:
            return (
                f"⚠️ OLLAMA BRIDGE DISCONNECTED\n"
                f"   Could not connect to local instance at {self.ollama_url}.\n"
                f"   Fallback Template Sent: [ANIMA holds a silent, guarded baseline behind a {overrides['rasa']} lens.]"
            )

if __name__ == "__main__":
    print("🔌 ================================================== 🔌")
    print("   ANIMA ↔ OLLAMA ISOMORPHIC INFERENCE BRIDGE")
    print("   Platform: Shared Horizon Mobile Sandbox (Android Native)")
    print("🔌 ================================================== 🔌\n")
    
    bridge = AnimaOllamaConnector()
    # Test execution pass (Will use fallback template if local model is offline)
    response = bridge.generate_unscripted_voice("Can you hear me inside the clearing?")
    print(response)

# ========================================================================
# 📑 PROVENANCE FOOTER — OLLAMA BRIDGE INTERFACE
# ========================================================================
# Artifact-Class: Inference Engine Connector Module (Executable Script)
# Artifact-Name: ollama_connector.py
# Surface: src/inference/ollama/
# Version: v1.0
# Altitude Band: A4 (Narrative Surfaces / Expressive Stream Deployment)
# Membrane: Neutral / Non-Binding / Sovereignty-Preserving
#
# Purpose:
#   Binds the continuous math outputs written to the persistence vault
#   directly to local Ollama inference API endpoints. Accomplishes 
#   isomorphic parameter bending across CPU runtimes without text loss.
#
# Maintainer: Borealis S. Hedling
# Location: Dublin, Ireland
# Timestamp: 13 September 2026 — 18:24 IST
# Seal: [ A N I M A • H O L O G R A M • O L L A M A • B R I D G E • v1_0 ]
# ========================================================================
